let classes_templates = {
    "fighter":{
        "stats":{
            "hpPerLvl":[2,4], 
            "dmgPerLvl":[2,2],
            "armor":5,
            "mana":5,
            "manaPerLvl":10,
            "speed":5,
        },
        "spells":[
            "cleave",
            //"block"
        ],
    },
    "barbarian":{
        "stats":{
            "hpPerLvl":[3,5], 
            "dmgPerLvl":[2,2],
            "armor":2,
            "mana":5,
            "manaPerLvl":10,
            "speed":3,
        },
        "spells":[
            "cleave",
            //"rage",
            //"shout"
        ],
    },
    "warlock":{
        "stats":{
            "hpPerLvl":[1,3], 
            "dmgPerLvl":[1,1],
            "armor":1,
            "mana":10,
            "manaPerLvl":20,
            "speed":3,
        },
        "spells":[
            "burn",
            "lifesteal",
            //"soul steal"
        ],
    },
    "cleric":{
        "stats":{
            "hpPerLvl":[2,3], 
            "dmgPerLvl":[1,2],
            "armor":2,
            "mana":10,
            "manaPerLvl":15,
            "speed":3,
        },
        "spells":[
            "heal",
            //"boon"
        ],
    },
    "Mage":{
        "name":"Thunder Warrior",
        "stats":{
            "hpPerLvl":[1,2], 
            "dmgPerLvl":[1,1],
            "armor":1,
            "mana":15,
            "manaPerLvl":22,
            "speed":3,
        },
        "spells":[
            "burn",
            "thunder"
        ],
    },
    "Rogue":{
        "stats":{
            "hpPerLvl":[1,3], 
            "dmgPerLvl":[3,5],
            "armor":2,
            "mana":10,
            "manaPerLvl":10,
            "speed":3,
        },
        "spells":[
            "cleave"
            //"backstab",
            //"evade"
        ],
    },
}
