let maps_img_names = [
'images/maps/new_map.png',
'images/maps/dungeon2.png',
'images/maps/new_map_1.png',
'images/maps/new_map_10.png',
'images/maps/new_map_12.png',
'images/maps/new_map_11.png',
'images/maps/new_map_2.png',
'images/maps/new_map_13.png',
'images/maps/new_map_3.png',
'images/maps/new_map_4.png',
'images/maps/new_map_5.png',
'images/maps/new_map_6.png',
'images/maps/new_map_8.png',
'images/maps/new_map_7.png',
'images/maps/orc_1.png',
'images/maps/new_map_9.png',
]
